### ISSUE TITLE
[bug report] bind_shell/reverse_shell will drop privilege in some cases

### ISSUE THREAD

**Issue by bash-c** [leommxj/prebuilt-multiarch-bin#5]
Both [bind_shell](https://github.com/leommxj/prebuilt-multiarch-bin/blob/src/src/shell/bind_shell.c#L52-L58) and [reverse_shell](https://github.com/leommxj/prebuilt-multiarch-bin/blob/src/src/shell/reverse_shell.c#L23-L27) will execute `/bin/sh` for an interactive shell, however, `sh` in some cases will drop privilege.

Add the following snippet will fix this
```C
if geteuid() == 0:
    setresuid(0, 0, 0);
    setresgid(0, 0, 0);

spawn /bin/sh and others
```

**Comment by bash-c** [comment]
BTW, there is a [typo](https://github.com/leommxj/prebuilt-multiarch-bin/blob/src/src/shell/reverse_shell.c#L12). the word `spwan` should be `spawn`

**Comment by leommxj** [comment]
@bash-c Done. Please ddw.
